<div class="xpec-col-30">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('maui-footer-contact')->toHtml(); ?>
</div>
<div class="xpec-col-20">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('maui-footer-help')->toHtml(); ?>
</div>
<div class="xpec-col-20">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('maui-footer-account')->toHtml(); ?>
</div>
<div class="xpec-col-30">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('maui-footer-newsletter')->toHtml(); ?>
</div>
