<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Ingresa tu email...') ?>" required/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Enviar') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Enviar') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
