<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if ($block->allowExtension()): ?>
    <script>

        require([
            'jquery',
            'ibnabmodernizr'
        ], function ($) {
            $('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');
            $('.menu > ul > li > ul:not(:has(ul))').addClass('normal-sub');
            $(".menu > ul").before("<a href=\"#\" class=\"menu-mobile\">Navigation</a>");

            /*$(".menu > ul > li").hover(function (e) {
                if ($(window).width() > 943) {
                    $(this).children("ul").stop(true, false).fadeToggle(150);
                    e.preventDefault();
                }
            })*/

            //Fix Menu Ibnab Working
            if ($(window).width() > 943) {
              $(".menu>ul>li").hover(function(){
                var $menu = $(this);
                $menu.attr('hoverIn','true');
                setTimeout(function(){
                  if($menu.attr('hoverIn') == 'true'){
                    $menu.children('ul').slideDown(150);
                  }
                }, 300);
              },
              function(){
                $(this).attr('hoverIn','false');
                $(this).children('ul').slideUp(150);
              });
            }
            //If width is more than 943px dropdowns are displayed on hover

            $(".menu > ul > li").click(function () {
                if ($(window).width() <= 943) {
                    $(this).children("ul").fadeToggle(150);
                }
            });
            //If width is less or equal to 943px dropdowns are displayed on click (thanks Aman Jain from stackoverflow)

            $(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                e.preventDefault();
            });

            if ($(".menu>ul>li:hover").length != 0) {
                $(".menu>ul>li").mouseleave(function(){
                    $(".menu>ul>li>ul").hide();
                });
            }

        });

    </script>
    <?php
    /**
     * Top menu for store
     *
     * @see \Magento\Theme\Block\Html\Topmenu
     */
    ?>
    <nav class="navigation" role="navigation" >

        <div class="menu" id="om">
            <ul>
                <?php /* @escapeNotVerified */ echo $_menu2; ?>
            </ul>
        </div>
        <ul id="dm" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>

<?php else : ?>

    <nav class="navigation" role="navigation">
<?php /* @escapeNotVerified */ echo $_menu; ?>
    </nav>
<?php endif; ?>
